[bumpver]
current_version = "0.1"
version_pattern = "MAJOR.MINOR[.PATCH[PYTAGNUM]]"
commit_message = "Update version from {old_version} to {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]

"src/main.rs" = [
    'static VERSION: &str = "{version}";',
]